### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB. GPU 0 has a total capacity of 15.70 GiB of which 27.94 MiB is free

### ISSUE THREAD

**Issue by Giancarlo1974** [itsrocchi/finetuning-llama2-ita#1]
Ho provato il codice, 

`python finetuner.py --dataset_name seeweb/Seeweb-it-292-forLLM --load_in_4bit --use_peft --batch_size 1 --gradient_accumulation_steps 1 --num_train_epochs 1
`
Va in errore quando invoca:

`#nuovo codice:
base_model = AutoModelForCausalLM.from_pretrained(
    'meta-llama/Llama-2-7b-chat-hf', #modello di base
    low_cpu_mem_usage=True,
    return_dict=True,
    torch_dtype=torch.float16,
    device_map=device_map,
)`

per problemi di memoria

>     base_model = AutoModelForCausalLM.from_pretrained(
>   File "/home/gianca/.pyenv/versions/finetuning-ita-env-3.9/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
>     return model_class.from_pretrained(
>   File "/home/gianca/.pyenv/versions/finetuning-ita-env-3.9/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3677, in from_pretrained
>     ) = cls._load_pretrained_model(
>   File "/home/gianca/.pyenv/versions/finetuning-ita-env-3.9/lib/python3.9/site-packages/transformers/modeling_utils.py", line 4104, in _load_pretrained_model
>     new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
>   File "/home/gianca/.pyenv/versions/finetuning-ita-env-3.9/lib/python3.9/site-packages/transformers/modeling_utils.py", line 886, in _load_state_dict_into_meta_model
>     set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
>   File "/home/gianca/.pyenv/versions/finetuning-ita-env-3.9/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 399, in set_module_tensor_to_device
>     new_value = value.to(device)
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB. GPU 0 has a total capacity of 15.70 GiB of which 19.94 MiB is free. Including non-PyTorch memory, this process has 15.67 GiB memory in use. Of the allocated memory 15.41 GiB is allocated by PyTorch, and 116.20 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

ho anche provato a risolvere, aggiungendo:

```
# os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:21"
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
torch.cuda.empty_cache()
```

mi sembra di capire che si pianta dopo l'allenamento

Come si potrebbe modificare il codice per salvare il modello allenato ?
Magari in locale

**Comment by itsrocchi** [comment]
Ciao! innanzitutto scusami ma non avevo proprio visto il messaggio. L'errore indica che la GPU non ha abbastanza memoria per completare il training del modello "_this process has 15.67 GiB memory in use._"

se hai provato altri metodi per mandare un batch piu piccolo di dati in training e ottieni lo stesso errore, semplicemente la gpu non è in linea con i requisiti. Prova a trainare un modello piu semplice magari. (il codice in origine è stato testato su una gpu con il triplo della memoria)
